apiVersion: apps/v1
kind: Deployment
metadata:
  name: pain
spec:
  selector:
    matchLabels:
      app: pain
  replicas: 2
  template:
    metadata:
      labels:
        app: pain
    spec:
      containers:
      - name: pain
        image: ifilyaninitmo/itdt-contained-frontend:master
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_USERNAME
          value: "Lily"
        - name: REACT_APP_COMPANY_NAME
          value: "LLM"
